<a href="https://colab.research.google.com/github/ssrbazpur/Data-Science/blob/master/Python_Data_Science_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h3> Basic of Python </h3>

In [1]:
#10 power of 2
10**2

100

In [2]:
10 *"str"

'strstrstrstrstrstrstrstrstrstr'

In [4]:
# type(1)
# type(True)
# control + / to uncomment
type("str")

str

In [7]:
first= "Simranjeet"
last="Randhawa"
print("My name is {first} {second}".format(first=first,second=last))

My name is Simranjeet Randhawa


In [9]:
len("hello world")

11

<h3> Data Types </h3>
<ul>
<li>Boolean</li>
<li>List</li>
<li>Dictionary</li>
<li>Tuples</li>
<li>Set</li>
</ul>

In [10]:
boolean=True
type(boolean)

bool

In [11]:
str="hello"
str.isupper()

False

<h4> List </h4>

In [12]:
list1=['hello',1,'world',2]
type(list1)

list

In [13]:
list1.append(100)
list1

['hello', 1, 'world', 2, 100]

In [15]:
list1.insert(1,"world")
list1[:]

['hello', 'world', 'world', 1, 'world', 2, 100]

In [0]:
list1.append(["hello","world"])
list1.extend(["hello","world"])
list1.pop(-3) #remove element.
list1[:]

In [31]:
temp=[1,2,3,4,5,6,7,8,90]
print(min(temp))
print(max(temp))
temp.index(2,0,7)


1
90


1

In [35]:
temp=temp*2
temp

[1, 2, 3, 4, 5, 6, 7, 8, 90, 1, 2, 3, 4, 5, 6, 7, 8, 90]

<h4> Set </h4>
<p> It has no duplicate values</p>

In [37]:
set1={"hello","world"}
type(set1)

set

In [0]:
set1.add(1)

In [42]:
#Iterate through set
for val in set1:
  print("Value is {}".format(val))

Value is hello
Value is world
Value is 1


<h4>Dictionary</h4>

In [44]:
dict1={"a":"hello",2:"bye","zoo":"game"}
type(dict1)

dict

In [46]:
dict1['zoo']

'game'

In [47]:
for key in dict1:
  print(key)

a
2
zoo


In [51]:
for x in dict1.values():
  print(x)

hello
bye
game


In [55]:
dict1[5]="new item"
dict1

{2: 'bye', 5: 'new item', 'a': 'hello', 'zoo': 'game'}

<h4>Tuple</h4>

In [56]:
new=("hi",1,"how")
type(new)

tuple

In [59]:
#new[0]="hello" #cannot replace vaues in tuples
new[0]

'hi'

<h3> Numpy for Data Science</h3>

In [0]:
import numpy as np
# Shift enter to run and move to next cell.

In [62]:
list1=[1,2,3,4,5,6,7,8,9,10]
array1=np.array(list1)
type(array1)

numpy.ndarray

In [64]:
array1.shape #1d array

(10,)

In [65]:
array1=[1,2,3,4]
array2=[5,6,7,8]
array3=[9,10,11,12]
final=np.array([array1,array2,array3])
final

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
final.shape

(3, 4)

In [70]:
final.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [71]:
final.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
final[0][0]

1

In [77]:
final[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
#first 2 rows and 2 columns
final[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [82]:
#Some Build in functions
array2=np.arange(0,10,2)
array2

array([0, 2, 4, 6, 8])

In [83]:
#Between 2 and 3 I want 5 division
np.linspace(2,3,5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [84]:
array2*2

array([ 0,  4,  8, 12, 16])

In [85]:
array2>2

array([False, False,  True,  True,  True])

In [86]:
array2[3:]=100
array2

array([  0,   2,   4, 100, 100])

In [87]:
array2[array2<100]

array([0, 2, 4])

In [88]:
np.ones(4)

array([1., 1., 1., 1.])

In [90]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [92]:
#Random DIstribution
np.random.rand(2,2)

array([[0.09106617, 0.08488594],
       [0.09866144, 0.63058193]])

In [93]:
a2=np.random.randn(3,3)
a2

array([[ 0.08236434, -1.57866524, -0.76208887],
       [ 1.02588416,  1.52401446,  1.736394  ],
       [ 2.41432041, -0.97408027, -0.61397756]])

In [95]:
np.random.randint(0,100,8).reshape(2,4)

array([[24, 90, 20, 25],
       [37, 85, 30, 26]])

In [97]:
np.random.random_sample((5,2))

array([[8.20344253e-01, 5.62264486e-02],
       [6.44102937e-01, 2.22214002e-01],
       [3.69682950e-01, 1.16568952e-02],
       [4.11660676e-01, 6.21480531e-01],
       [5.36780375e-04, 9.10527672e-01]])

<h3>Pandas for Data Science </h3>

In [0]:
import pandas as pd

In [0]:
df=pd.DataFrame(np.arange(0,100,5).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['first','second','third','fourth'])

In [104]:
df.head()

first  second  third  fourth
row1      0       5     10      15
row2     20      25     30      35
row3     40      45     50      55
row4     60      65     70      75
row5     80      85     90      95

In [105]:
df

first  second  third  fourth
row1      0       5     10      15
row2     20      25     30      35
row3     40      45     50      55
row4     60      65     70      75
row5     80      85     90      95

In [0]:
df.to_csv("hello.csv")

In [107]:
#Accessing elements
#1. .loc->location 2. iloc->index
df.loc['row1']

first      0
second     5
third     10
fourth    15
Name: row1, dtype: int64

In [109]:
type(df.loc['row2'])

pandas.core.series.Series

In [110]:
df.iloc[:,:]

first  second  third  fourth
row1      0       5     10      15
row2     20      25     30      35
row3     40      45     50      55
row4     60      65     70      75
row5     80      85     90      95

In [112]:
#convert dataframe to array
df.iloc[:,:].values

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [118]:
#Coutn values in columns.
df['first'].value_counts()


80    1
40    1
20    1
60    1
0     1
Name: first, dtype: int64

In [119]:
df["second"].unique()

array([ 5, 25, 45, 65, 85])

In [121]:
type(df["second"])

pandas.core.series.Series

In [124]:
df[["second","first"]]

second  first
row1       5      0
row2      25     20
row3      45     40
row4      65     60
row5      85     80

In [125]:
type(df[["second","first"]])

pandas.core.frame.DataFrame